
#include "Update_SliceDnnCntSQL.hpp"

/*-

UPDATE T_SLICE_DNN_CNT SET HOST_NAME=? NOW_CNT=?, REJECTING=(
SELECT CASE
  WHEN REJECT_SET_CNT <= ? THEN 1
  WHEN REJECT_REL_CNT < ? AND REJECTING=1 THEN 1
  WHEN REJECT_REL_CNT < ? AND REJECTING=0 THEN 0
  ELSE 0
  END AS VAL 
FROM T_SLICE_DNN_CNT WHERE SST=? AND SD=? AND DNN=?)
 WHERE SST=? AND SD=? AND DNN=? AND USED=1;

-*/